require:
  - rubocop/cop/internal_affairs
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - workitcop

AllCops:
  TargetRubyVersion: 2.6
  SuggestExtensions: false
  NewCops: enable

Layout/LineLength:
  Enabled: false

Metrics:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

RSpec/ExampleLength:
  Enabled: false

RSpec/SpecFilePathFormat:
  Exclude:
    - spec/rubocop/cop/workit/rspec*.rb
