---
inherit_mode:
  merge:
    - Exclude

Workit/ActionArgs:
  Description: |
    Check for controller action must be using `action_args`.
  Enabled: false
  Include:
    - "controllers/**/*"
  ControllerMethods:
    - index
    - show
    - create
    - update
    - cancel
    - destroy

Workit/NoopRescue:
  Description: "Check for suppress or ignore checked exception."
  Enabled: false

Workit/RedundantBooleanConditional:
  Description: "Checks for redundant boolean conditions."
  Enabled: false

Workit/RestrictOnSend:
  Description: |
    Check for `RESTRICT_ON_SEND` is defined if `on_send` or `after_send` are defined.
  Enabled: false

Workit/RSpecRedundantHttpStatus:
  Description: Check for validation of redundant response HTTP status codes.
  Enabled: false
